"use strict";

function mapping() {
  return {
    "0": "0",
    "1": "1",
    "2": "2",
    "3": "3",
    "4": "4",
    "5": "5",
    "6": "6",
    "7": "7",
    "8": "8",
    "9": "9",
    "Channel Up": "10",
    "Channel Down": "11",
    Play: "12",
    Pause: "13",
    "Play / Pause (Toggle)": "14",
    Stop: "15",
    Forward: "16",
    "Skip Forward": "17",
    Rewind: "18",
    "Skip Backward": "19",
    Record: "20",
    Up: "21",
    Down: "22",
    Left: "23",
    Right: "24",
    "Select / Enter / OK": "25",
    "Back / Return / Cancel": "26",
    Menu: "27",
    Home: "28",
    "TV Guide": "29",
    Red: "30",
    Green: "31",
    Yellow: "32",
    Blue: "33",
    "Volume Up": "34",
    "Volume Down": "35",
    "Mute (Toggle)": "36",
    Info: "37",
    "Power (Toggle)": "38",
    "Power Off (Explicit)": "39",
    Subtitles: "40",
    Source: "41",
    Eject: "42",
    Audio: "43",
    "3D": "44",
    "Top Menu": "45",
    "Pop-up Menu": "46",
    "Aspect Ratio": "47",
    Help: "48",
    "Power On (Explicit)": "49",
    "No / Thumbs Down": "50",
    "Yes / Thumbs Up": "51",
    "Page Up": "52",
    "Page Down": "53",
    Search: "54",
    Exit: "55",
    "Catch Up": "56",
    Playlist: "57",
    "Box Office": "58",
    DSTV: "59"
  };
}

module.exports = {
  mapping
};
